# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: the2app CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_front:
    
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./client

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run build 
    #- run: npm test
    - name: build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: omwalid/the2app_front
        dockerfile: ./client/Dockerfile 
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
  build_back:
    
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./server

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: omwalid/the2app_back
        dockerfile: ./server/Dockerfile 
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
